linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - staticcheck
    - unused

run:
  timeout: 5m

issues:
  exclude-dirs:
    - sdk/typescript/node_modules
    - sdk/typescript/dist
  max-issues-per-linter: 0
  max-same-issues: 0
